name: Build

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - name: Prepare things
        id: prepare
        run: |
          mkdir artifacts

          # Extract version from tag
          VERSION=$(git tag --points-at HEAD | head -n1)
          if [[ "$VERSION" != "" ]]; then
            echo "Release $VERSION of ${{ github.sha }}" > RELEASE.txt
            echo >> RELEASE.txt
          fi

      - name: Build for Linux amd64
        run: |
          go build -o artifacts/zappac-linux-amd64

      - name: Build for Linux arm64
        run: |
          GOARCH=arm64 go build -o artifacts/zappac-linux-arm64

      - name: Build for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o artifacts/zappac-windows-amd64.exe

      - name: Build for Windows arm64
        run: |
          GOOS=windows GOARCH=arm64 go build -o artifacts/zappac-windows-arm64.exe

      # TODO: macOS build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts

      # Release tagged pushes
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE.txt
          files: artifacts/*
