name: Test

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - name: Build
        run: go build -o zappac
